// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/tir/code/miku/cgosamples/x/xcgobasic/main.go:1:1
package main

/*

#include <stdio.h>
#include <stdlib.h>

void print_name(char* s)
{
    printf("%s\n", s);
}

*/
import _ "unsafe"
import "fmt"

func main() {
	fmt.Println("vim-go")
}
